// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATSJWx9BLUnB85rJwTFmVpW2BY38a3M04',
    appId: '1:733397364079:web:c54715386f2664522e0c9a',
    messagingSenderId: '733397364079',
    projectId: 'timesheet-app-f1f5f',
    authDomain: 'timesheet-app-f1f5f.firebaseapp.com',
    storageBucket: 'timesheet-app-f1f5f.appspot.com',
    measurementId: 'G-5ZMQPMR519',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2xGzOzfMN_D4tXGEfUbUpIhGdMcjlLsE',
    appId: '1:733397364079:android:453f0632e1d5a7d02e0c9a',
    messagingSenderId: '733397364079',
    projectId: 'timesheet-app-f1f5f',
    storageBucket: 'timesheet-app-f1f5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm__Q1wuV_qM2KgJ6P4gYTlCEdda3-K8Y',
    appId: '1:733397364079:ios:81b9757ef9acd12b2e0c9a',
    messagingSenderId: '733397364079',
    projectId: 'timesheet-app-f1f5f',
    storageBucket: 'timesheet-app-f1f5f.appspot.com',
    iosBundleId: 'com.example.timesheetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm__Q1wuV_qM2KgJ6P4gYTlCEdda3-K8Y',
    appId: '1:733397364079:ios:81b9757ef9acd12b2e0c9a',
    messagingSenderId: '733397364079',
    projectId: 'timesheet-app-f1f5f',
    storageBucket: 'timesheet-app-f1f5f.appspot.com',
    iosBundleId: 'com.example.timesheetApp',
  );
}
